"""Derived owner-key migration and writer checks on disposable PostgreSQL."""
import importlib.util
from pathlib import Path
from unittest.mock import Mock

import psycopg
import pytest

from test_owner_ingestion import database as database_fixture, ingestion as ingestion_fixture, message
from gmail_search import propositions
from gmail_search.store import queries

database = database_fixture
ingestion = ingestion_fixture


@pytest.fixture
def derived(ingestion):
    conn, owners = ingestion
    conn.execute('ALTER TABLE propositions ALTER COLUMN id SET NOT NULL, ALTER COLUMN user_id SET NOT NULL, ALTER COLUMN message_id SET NOT NULL')
    conn.execute('ALTER TABLE propositions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY')
    conn.execute('ALTER TABLE propositions ADD PRIMARY KEY(id), ADD COLUMN embedding bytea')
    conn.execute('CREATE TABLE prop_processed(user_id text, message_id text, PRIMARY KEY(user_id,message_id))')
    return conn, owners


def migration_module():
    path = Path(__file__).parents[1]/'deploy/public/migrate_derived_owner_keys.py'
    spec = importlib.util.spec_from_file_location('derived_owner_keys', path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_foreign_parent_is_refused_before_embedding(derived):
    conn, (alice, bob) = derived
    queries.upsert_message(conn, message(alice), user_id=alice)
    embedder = Mock(model='synthetic')
    embedder.embed_texts_batch.return_value = [[1., 2.]]
    with pytest.raises(ValueError, match='owner'):
        propositions.store_propositions(conn, embedder, user_id=bob, message_id='collision', thread_id='thread', date=None, facts=['fact'])
    embedder.embed_texts_batch.assert_not_called()
    assert conn.execute('SELECT count(*) AS n FROM propositions').fetchone()['n'] == 0


def test_derived_migration_cascades_only_deleted_owner_and_is_idempotent(derived):
    conn, (alice, bob) = derived
    migration = migration_module()
    for owner in (alice, bob):
        queries.upsert_message(conn, message(owner), user_id=owner)
        conn.execute("INSERT INTO propositions(user_id,message_id,text,model) VALUES(%s,'collision',%s,'synthetic')", (owner, owner))
        conn.execute("INSERT INTO prop_processed VALUES(%s,'collision')", (owner,))
    assert migration.migrate_derived_owner_keys(conn)
    assert not migration.migrate_derived_owner_keys(conn)
    for table in ('propositions', 'prop_processed'):
        with pytest.raises(psycopg.errors.ForeignKeyViolation):
            if table == 'propositions':
                conn.execute("INSERT INTO propositions(user_id,message_id,text,model) VALUES(%s,'missing','foreign','synthetic')", (alice,))
            else:
                conn.execute("INSERT INTO prop_processed VALUES(%s,'missing')", (alice,))
    conn.execute("DELETE FROM messages WHERE user_id=%s AND id='collision'", (alice,))
    assert conn.execute('SELECT user_id,text FROM propositions').fetchall() == [{'user_id': bob, 'text': bob}]
    assert conn.execute('SELECT user_id FROM prop_processed').fetchall() == [{'user_id': bob}]


def test_orphan_refuses_migration_without_partial_constraints(derived):
    conn, (alice, _) = derived
    conn.execute("INSERT INTO propositions(user_id,message_id,text,model) VALUES(%s,'missing','fact','synthetic')", (alice,))
    with pytest.raises(ValueError, match='orphan'):
        migration_module().migrate_derived_owner_keys(conn)
    assert conn.execute("SELECT count(*) AS n FROM pg_constraint WHERE conrelid='propositions'::regclass AND contype='f'").fetchone()['n'] == 0


def test_pending_derived_markers_and_facts_stay_owner_scoped(derived, monkeypatch):
    conn, (alice, bob) = derived
    migration_module().migrate_derived_owner_keys(conn)
    for owner in (alice, bob):
        queries.upsert_message(conn, message(owner), user_id=owner)
    monkeypatch.setattr(propositions, 'extract_propositions', lambda *args, **kwargs: ['fact'])
    embedder = Mock(model='synthetic')
    embedder.embed_texts_batch.return_value = [[1., 2.]]
    assert propositions.propositionize_pending(conn, None, None, embedder, user_id=alice, owner='Alice')['facts'] == 1
    assert conn.execute('SELECT user_id FROM propositions').fetchall() == [{'user_id': alice}]
    assert conn.execute('SELECT user_id FROM prop_processed').fetchall() == [{'user_id': alice}]


from test_owner_key_schema_migration import legacy_schema as legacy_schema_fixture, migration as main_migration_fixture
legacy_schema = legacy_schema_fixture
main_migration = main_migration_fixture


def test_main_migration_reapplies_after_derived_keys(legacy_schema, main_migration):
    conn = legacy_schema
    main_migration.migrate_owner_keys(conn)
    conn.execute('CREATE TABLE propositions(id bigserial PRIMARY KEY,user_id text NOT NULL,message_id text NOT NULL)')
    conn.execute('CREATE TABLE prop_processed(user_id text,message_id text,PRIMARY KEY(user_id,message_id))')
    assert migration_module().migrate_derived_owner_keys(conn)
    assert not main_migration.migrate_owner_keys(conn)


def test_parent_deleted_during_embedding_does_not_create_legacy_orphan(derived):
    conn, (alice, _) = derived
    queries.upsert_message(conn, message(alice), user_id=alice)
    embedder = Mock(model='synthetic')
    def deleting(facts):
        conn.execute('DELETE FROM messages WHERE user_id=%s', (alice,))
        return [[1., 2.]]
    embedder.embed_texts_batch.side_effect = deleting
    with pytest.raises(ValueError, match='owner'):
        propositions.store_propositions(conn, embedder, user_id=alice, message_id='collision', thread_id='thread', date=None, facts=['fact'])
    assert conn.execute('SELECT count(*) AS n FROM propositions').fetchone()['n'] == 0


def test_target_schema_refuses_nullable_owner_regression(derived):
    conn, _ = derived
    migration_module().migrate_derived_owner_keys(conn)
    conn.execute('ALTER TABLE propositions ALTER COLUMN user_id DROP NOT NULL')
    with pytest.raises(ValueError, match='nullability'):
        migration_module().migrate_derived_owner_keys(conn)


def test_migration_preserves_existing_policies_and_grants(derived):
    conn, _ = derived
    def snapshot():
        return conn.execute("SELECT relacl,relrowsecurity,relforcerowsecurity FROM pg_class WHERE oid='propositions'::regclass").fetchone(), conn.execute("SELECT polname,pg_get_expr(polqual,polrelid) AS expression FROM pg_policy WHERE polrelid='propositions'::regclass").fetchall()
    before = snapshot()
    migration_module().migrate_derived_owner_keys(conn)
    assert snapshot() == before


def test_null_owner_and_unexpected_unique_index_are_refused(derived):
    conn, _ = derived
    conn.execute('ALTER TABLE propositions ALTER COLUMN user_id DROP NOT NULL')
    conn.execute("INSERT INTO propositions(user_id,message_id,text,model) VALUES(NULL,'missing','fact','synthetic')")
    with pytest.raises(ValueError, match='null'):
        migration_module().migrate_derived_owner_keys(conn)
    conn.execute('DELETE FROM propositions')
    conn.execute('CREATE UNIQUE INDEX unsupported_derived_identity ON propositions(message_id)')
    with pytest.raises(ValueError, match='unique index'):
        migration_module().migrate_derived_owner_keys(conn)
