"""Owner-qualified ingestion against disposable PostgreSQL, with colliding Gmail IDs."""
from datetime import datetime, timezone

import psycopg
from psycopg.rows import dict_row
import pytest

from test_gateway_database_integration import database as database_fixture
from gmail_search.store import queries
from gmail_search.store.models import Attachment, Message

database = database_fixture


def message(subject):
    return Message('collision', 'thread', 'sender@example.test', 'to@example.test', subject,
                   subject, '', datetime(2026, 1, 1, tzinfo=timezone.utc), [], 1, '{}')


@pytest.fixture
def ingestion(database):
    dsn, owners = database
    with psycopg.connect(dsn, autocommit=True, row_factory=dict_row) as conn:
        conn.execute('DELETE FROM messages')
        conn.execute('ALTER TABLE messages ADD PRIMARY KEY (user_id,id)')
        conn.execute("ALTER TABLE messages ADD COLUMN body_html text DEFAULT '', ADD COLUMN history_id bigint DEFAULT 0, ADD COLUMN crawl_blocked_reason text")
        conn.execute('ALTER TABLE attachments ALTER COLUMN id SET NOT NULL')
        conn.execute('ALTER TABLE attachments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY')
        conn.execute('ALTER TABLE attachments ADD PRIMARY KEY (id), ADD UNIQUE (user_id,message_id,filename), ADD UNIQUE (user_id,message_id,id), ADD FOREIGN KEY (user_id,message_id) REFERENCES messages(user_id,id)')
        conn.execute("ALTER TABLE attachments ADD COLUMN image_path text, ADD COLUMN raw_path text, ADD COLUMN embed_attempts int DEFAULT 0, ADD COLUMN embed_error text, ADD COLUMN embed_status text")
        conn.execute('ALTER TABLE thread_summary ADD UNIQUE (thread_id,user_id)')
        conn.execute('CREATE TABLE embeddings (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id text NOT NULL, message_id text, attachment_id bigint, chunk_type text, chunk_text text, embedding bytea, model text, FOREIGN KEY(user_id,message_id) REFERENCES messages(user_id,id), FOREIGN KEY(user_id,message_id,attachment_id) REFERENCES attachments(user_id,message_id,id))')
        yield conn, owners


def test_colliding_messages_and_all_attachment_writers(ingestion):
    conn, (alice, bob) = ingestion
    for owner in (alice, bob):
        queries.upsert_message(conn, message(owner), user_id=owner)
        queries.upsert_attachment(conn, Attachment(None, 'collision', 'doc', 'text/plain', 2, raw_path='/synthetic/' + owner), user_id=owner)
        queries.record_unfetched_attachment(conn, message_id='collision', filename='missing', mime_type='text/plain', size_bytes=3, fetch_status='fetch_failed', user_id=owner)
        assert queries.upsert_drive_stub(conn, message_id='collision', drive_id='drive', mime_type='application/vnd.google-apps.document', user_id=owner) == 1
        assert queries.upsert_url_stub(conn, message_id='collision', url='https://example.test', user_id=owner) == 1
    queries.upsert_message(conn, message('updated'), user_id=alice)
    assert queries.get_message(conn, 'collision', user_id=alice).subject == 'updated'
    assert queries.get_message(conn, 'collision', user_id=bob).subject == bob
    assert len(queries.get_attachments_for_message(conn, 'collision', user_id=alice)) == 4
    assert len(queries.get_attachments_for_message(conn, 'collision', user_id=bob)) == 4
    assert conn.execute('SELECT count(*) AS n FROM thread_summary WHERE thread_id=%s', ('thread',)).fetchone()['n'] == 2


def test_foreign_child_and_foreign_attachment_update_are_refused(ingestion):
    conn, (alice, bob) = ingestion
    queries.upsert_message(conn, message(alice), user_id=alice)
    att = Attachment(None, 'collision', 'doc', 'text/plain', 2, raw_path='/synthetic/alice')
    aid = queries.upsert_attachment(conn, att, user_id=alice)
    with pytest.raises(psycopg.errors.ForeignKeyViolation):
        queries.upsert_attachment(conn, att, user_id=bob)
    queries.fill_drive_attachment(conn, attachment_id=aid, title='foreign', text='foreign', drive_id='drive', user_id=bob)
    queries.fill_url_attachment(conn, attachment_id=aid, title='foreign', text='foreign', url='https://example.test', user_id=bob)
    assert queries.record_image_embed_failure(conn, aid, 'foreign', permanent=True, max_attempts=1, user_id=bob) is None
    assert conn.execute('SELECT extracted_text FROM attachments WHERE id=%s', (aid,)).fetchone()['extracted_text'] is None
    queries.fill_drive_attachment(conn, attachment_id=aid, title='own', text='own', drive_id='drive', user_id=alice)
    assert conn.execute('SELECT extracted_text FROM attachments WHERE id=%s', (aid,)).fetchone()['extracted_text'] == 'own'


def test_crawl_cache_and_embedding_existence_are_owner_scoped(ingestion):
    conn, (alice, bob) = ingestion
    for owner in (alice, bob):
        queries.upsert_message(conn, message(owner), user_id=owner)
    queries.set_crawl_blocked_reason(conn, message_id='collision', reason='private', user_id=alice)
    assert queries.get_crawl_blocked_reason(conn, message_id='collision', user_id=bob) is None
    assert queries.get_crawl_blocked_reason(conn, message_id='collision', user_id=alice) == 'private'
    conn.execute("INSERT INTO embeddings(user_id,message_id,chunk_type,model) VALUES(%s,'collision','message','model')", (alice,))
    assert queries.embedding_exists(conn, 'collision', None, 'message', 'model', user_id=alice)
    assert not queries.embedding_exists(conn, 'collision', None, 'message', 'model', user_id=bob)
    assert [m.id for m in queries.get_messages_without_embeddings(conn, 'model', user_id=bob)] == ['collision']


def test_omitted_owner_uses_bootstrap_without_cross_owner_reads(ingestion, monkeypatch):
    conn, (alice, bob) = ingestion
    monkeypatch.setattr('gmail_search.auth.write_user.get_bootstrap_user_id', lambda conn: alice)
    for owner in (alice, bob):
        queries.upsert_message(conn, message(owner), user_id=owner)
    queries.upsert_attachment(conn, Attachment(None, 'collision', 'bob-only', 'text/plain', 2, raw_path='/synthetic/bob'), user_id=bob)
    assert queries.get_message(conn, 'collision').subject == alice
    assert queries.get_message_bodies_bulk(conn, ['collision']) == {'collision': alice}
    assert queries.get_attachments_for_message(conn, 'collision') == []
    assert queries.get_pending_extraction_message_ids(conn) == []
    assert queries.extract_attachment_on_demand(conn, 1, config={}) is None


def test_embeddings_refuse_missing_or_foreign_parent(ingestion):
    from gmail_search.store.models import EmbeddingRecord
    conn, (alice, bob) = ingestion
    queries.upsert_message(conn, message(alice), user_id=alice)
    aid = queries.upsert_attachment(conn, Attachment(None, 'collision', 'doc', 'text/plain', 2), user_id=alice)
    rec = EmbeddingRecord(None, 'collision', aid, 'attachment_text', 'text', b'1234', 'model')
    with pytest.raises(ValueError, match='owner'):
        queries.insert_embedding(conn, rec, user_id=bob)
    queries.upsert_message(conn, message(bob), user_id=bob)
    with pytest.raises(ValueError, match='owner'):
        queries.insert_embedding(conn, rec, user_id=bob)
    assert queries.insert_embedding(conn, rec, user_id=alice) > 0
    assert queries.load_all_embeddings(conn, 'model', user_id=bob) == ([], [])
    assert len(queries.load_all_embeddings(conn, 'model', user_id=alice)[0]) == 1
