"""Explicit single-owner heap attach rehearsal on disposable pg_search only."""
import importlib.util
import os
from pathlib import Path
import secrets

import psycopg
from psycopg import sql
from psycopg.conninfo import conninfo_to_dict, make_conninfo
import pytest

from gmail_search.gateway.partitions import PARTITION_SCHEMA, partition_name


@pytest.fixture
def migration():
    path = Path(__file__).parents[1] / 'deploy/public/migrate_owner_partitions.py'
    spec = importlib.util.spec_from_file_location('owner_partition_migration', path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.fixture
def source():
    dsn = os.environ.get('GMS_RANKED_PROBE_DSN')
    if not dsn:
        pytest.skip('Requires explicit disposable loopback55440 DSN')
    cfg = conninfo_to_dict(dsn)
    assert cfg['host'] == '127.0.0.1' and cfg['port'] == '55440' and cfg['dbname'] == 'postgres'
    assert 'service' not in cfg and cfg.get('hostaddr','127.0.0.1') == '127.0.0.1'
    name = 'gms_owner_partitions_test_' + secrets.token_hex(8)
    with psycopg.connect(dsn, autocommit=True) as admin:
        assert admin.info.hostaddr == '127.0.0.1'
        admin.execute(sql.SQL('CREATE DATABASE {} TEMPLATE template0').format(sql.Identifier(name)))
    target = make_conninfo(dsn, dbname=name)
    try:
        with psycopg.connect(target, autocommit=True) as conn:
            conn.execute('CREATE EXTENSION pg_search')
            conn.execute('''
                CREATE TABLE users(id text PRIMARY KEY);
                INSERT INTO users VALUES('alice'),('bob');
                CREATE TABLE messages(id text NOT NULL,user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    search_id bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
                    thread_id text NOT NULL,subject text NOT NULL DEFAULT '',body_text text NOT NULL DEFAULT '',
                    from_addr text NOT NULL,to_addr text NOT NULL,body_html text NOT NULL DEFAULT '',
                    PRIMARY KEY(user_id,id));
                CREATE TABLE attachments(id bigserial PRIMARY KEY,user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    message_id text NOT NULL,filename text NOT NULL,mime_type text NOT NULL,extracted_text text,
                    FOREIGN KEY(user_id,message_id) REFERENCES messages(user_id,id),
                    UNIQUE(user_id,message_id,filename),UNIQUE(user_id,message_id,id));
                CREATE TABLE propositions(id bigserial PRIMARY KEY,user_id text NOT NULL,message_id text NOT NULL,
                    text text NOT NULL,embedding bytea,model text NOT NULL,created_at timestamptz DEFAULT now(),
                    FOREIGN KEY(user_id,message_id) REFERENCES messages(user_id,id) ON DELETE CASCADE);
                CREATE TABLE embeddings(id bigserial PRIMARY KEY,user_id text NOT NULL REFERENCES users(id),
                    message_id text NOT NULL,attachment_id bigint,embedding bytea,
                    FOREIGN KEY(user_id,message_id) REFERENCES messages(user_id,id),
                    FOREIGN KEY(user_id,message_id,attachment_id) REFERENCES attachments(user_id,message_id,id));
                CREATE TABLE message_topics(user_id text NOT NULL,message_id text NOT NULL,topic_id text NOT NULL,
                    PRIMARY KEY(user_id,message_id,topic_id),FOREIGN KEY(user_id,message_id) REFERENCES messages(user_id,id));
                CREATE TABLE message_summaries(user_id text NOT NULL,message_id text NOT NULL,summary text,
                    PRIMARY KEY(user_id,message_id),FOREIGN KEY(user_id,message_id) REFERENCES messages(user_id,id));
                CREATE TABLE summary_failures(user_id text NOT NULL,message_id text NOT NULL,error text,
                    PRIMARY KEY(user_id,message_id),FOREIGN KEY(user_id,message_id) REFERENCES messages(user_id,id) ON DELETE CASCADE);
                CREATE TABLE prop_processed(user_id text NOT NULL,message_id text NOT NULL,PRIMARY KEY(user_id,message_id),
                    FOREIGN KEY(user_id,message_id) REFERENCES messages(user_id,id) ON DELETE CASCADE);
                INSERT INTO messages(id,user_id,thread_id,subject,body_text,from_addr,to_addr)
                    VALUES('same','alice','thread','needle','original body','sender','recipient');
                INSERT INTO attachments(user_id,message_id,filename,mime_type,extracted_text)
                    VALUES('alice','same','file','text/plain',NULL);
                INSERT INTO propositions(user_id,message_id,text,embedding,model)
                    VALUES('alice','same','needle fact','\\x010203','synthetic');
                INSERT INTO embeddings(user_id,message_id,attachment_id,embedding) VALUES('alice','same',1,'\\x0102');
                INSERT INTO message_topics VALUES('alice','same','topic');
                INSERT INTO message_summaries VALUES('alice','same','summary');
                INSERT INTO summary_failures VALUES('alice','same','failure');
                INSERT INTO prop_processed VALUES('alice','same');
                CREATE INDEX messages_bm25_idx ON messages USING bm25(search_id,id,subject,body_text,from_addr,to_addr) WITH(key_field='search_id');
                CREATE INDEX attachments_bm25_idx ON attachments USING bm25(id,filename,extracted_text) WITH(key_field='id');
                CREATE INDEX props_bm25_idx ON propositions USING bm25(id,text) WITH(key_field='id');
                CREATE INDEX idx_props_msg ON propositions(message_id);
                COMMENT ON TABLE messages IS 'synthetic comment';
                COMMENT ON COLUMN propositions.embedding IS 'synthetic vector';
            ''')
            for table in ('messages','attachments','propositions'):
                ident = sql.Identifier(table)
                conn.execute(sql.SQL('ALTER TABLE {} ENABLE ROW LEVEL SECURITY').format(ident))
                conn.execute(sql.SQL('ALTER TABLE {} FORCE ROW LEVEL SECURITY').format(ident))
                conn.execute(sql.SQL("CREATE POLICY existing ON {} USING(user_id='alice') WITH CHECK(user_id='alice')").format(ident))
            yield conn
    finally:
        with psycopg.connect(dsn, autocommit=True) as admin:
            admin.execute(sql.SQL('DROP DATABASE {} WITH(FORCE)').format(sql.Identifier(name)))


def rows(conn, table):
    return conn.execute(sql.SQL('SELECT * FROM public.{} ORDER BY user_id,id').format(sql.Identifier(table))).fetchall()


def test_preview_is_read_only_and_attach_preserves_heaps_rows_indexes(source, migration):
    before = {table: rows(source, table) for table in ('messages','attachments','propositions')}
    identities = source.execute("SELECT relname,oid,relfilenode FROM pg_class WHERE oid IN ('messages'::regclass,'attachments'::regclass,'propositions'::regclass,'messages_bm25_idx'::regclass,'attachments_bm25_idx'::regclass,'props_bm25_idx'::regclass,'idx_props_msg'::regclass)").fetchall()
    preview = migration.preview_owner_partitions(source, owner_id='alice')
    assert preview['mode'] == 'attach_single_owner'
    assert len(preview['source_inventory']) == 3
    assert all(item['row_count']==1 and item['heap_bytes']>0 for item in preview['source_inventory'])
    assert source.execute("SELECT relkind FROM pg_class WHERE oid='messages'::regclass").fetchone() == ('r',)
    assert migration.migrate_owner_partitions(source, owner_id='alice') is True
    for table, original in before.items():
        assert rows(source, table) == original
        child = PARTITION_SCHEMA + '.' + partition_name(table, 'alice')
        old = next(item for item in identities if item[0] == table)
        assert source.execute('SELECT oid,relfilenode FROM pg_class WHERE oid=%s::regclass', (child,)).fetchone() == old[1:]
    for index in (item for item in identities if item[0].endswith('_idx') or item[0]=='idx_props_msg'):
        assert source.execute('SELECT relfilenode FROM pg_class WHERE oid=%s', (index[1],)).fetchone() == (index[2],)
    assert source.execute("SELECT id FROM messages WHERE user_id='alice' AND search_id @@@ 'subject:needle'").fetchall() == [('same',)]
    assert migration.migrate_owner_partitions(source, owner_id='alice') is False


def test_target_ids_are_owner_qualified_and_incoming_fks_reference_parents(source, migration):
    migration.migrate_owner_partitions(source, owner_id='alice')
    for table in ('messages','attachments','propositions'):
        source.execute(sql.SQL('CREATE TABLE {}.{} PARTITION OF public.{} FOR VALUES IN ({})').format(
            sql.Identifier(PARTITION_SCHEMA), sql.Identifier(partition_name(table,'bob')), sql.Identifier(table), sql.Literal('bob')))
    source.execute("INSERT INTO messages(id,user_id,search_id,thread_id,from_addr,to_addr) VALUES('same','bob',1,'thread','b','b')")
    source.execute("INSERT INTO attachments(id,user_id,message_id,filename,mime_type) VALUES(1,'bob','same','file','text/plain')")
    source.execute("INSERT INTO propositions(id,user_id,message_id,text,model) VALUES(1,'bob','same','bob fact','synthetic')")
    assert source.execute('SELECT count(*) FROM attachments WHERE id=1').fetchone() == (2,)
    source.execute("INSERT INTO embeddings(user_id,message_id,attachment_id) VALUES('bob','same',1)")
    with pytest.raises(psycopg.errors.UniqueViolation):
        source.execute("INSERT INTO attachments(id,user_id,message_id,filename,mime_type) VALUES(1,'bob','same','other','text/plain')")
    with pytest.raises(psycopg.errors.ForeignKeyViolation):
        source.execute("INSERT INTO propositions(user_id,message_id,text,model) VALUES('bob','missing','bad','synthetic')")
    new_id = source.execute("INSERT INTO messages(id,user_id,thread_id,from_addr,to_addr) VALUES('new','alice','thread','a','a') RETURNING search_id").fetchone()[0]
    assert new_id > 1


def test_failure_after_rename_rolls_back_every_object(source, migration):
    before = {table: rows(source, table) for table in ('messages','attachments','propositions')}
    def fail(stage):
        if stage == 'renamed':
            raise RuntimeError('synthetic rollback')
    with pytest.raises(RuntimeError, match='synthetic rollback'):
        migration.migrate_owner_partitions(source, owner_id='alice', _checkpoint=fail)
    assert source.execute("SELECT to_regnamespace(%s)", (PARTITION_SCHEMA,)).fetchone() == (None,)
    for table, original in before.items():
        assert rows(source, table) == original
    assert source.execute("SELECT id FROM messages WHERE search_id @@@ 'subject:needle'").fetchall() == [('same',)]


def test_populated_multiple_owners_refused_without_rewrite(source, migration):
    source.execute("INSERT INTO messages(id,user_id,thread_id,from_addr,to_addr) VALUES('same','bob','thread','b','b')")
    with pytest.raises(ValueError, match='owner'):
        migration.migrate_owner_partitions(source, owner_id='alice')
    assert source.execute("SELECT relkind FROM pg_class WHERE oid='messages'::regclass").fetchone() == ('r',)


@pytest.mark.parametrize('statement', [
    'CREATE VIEW unexpected AS SELECT id FROM messages',
    'CREATE TABLE unexpected(message_id text,user_id text,FOREIGN KEY(user_id,message_id) REFERENCES messages(user_id,id))',
    'CREATE INDEX unexpected ON messages(lower(subject))',
])
def test_unknown_dependencies_refused(source, migration, statement):
    source.execute(statement)
    with pytest.raises(ValueError):
        migration.migrate_owner_partitions(source, owner_id='alice')


@pytest.mark.parametrize('statement', [
    'ALTER TABLE summary_failures DROP CONSTRAINT summary_failures_user_id_message_id_fkey',
    "CREATE FUNCTION public.unexpected_default() RETURNS text LANGUAGE sql IMMUTABLE AS $$ SELECT 'x'::text $$; ALTER TABLE messages ALTER COLUMN subject SET DEFAULT public.unexpected_default()",
    "CREATE TABLE unexpected(id bigint DEFAULT nextval('attachments_id_seq'))",
    'ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO PUBLIC',
    'ALTER SEQUENCE attachments_id_seq CYCLE',
    'GRANT USAGE ON SEQUENCE attachments_id_seq TO PUBLIC',
    'ALTER TABLE messages ADD COLUMN unexpected text',
    'CREATE STATISTICS unexpected ON subject,body_text FROM messages',
    "CREATE POLICY unexpected ON messages USING(EXISTS(SELECT 1 FROM users))",
    "DROP POLICY existing ON propositions; ALTER TABLE propositions ALTER COLUMN user_id TYPE text COLLATE \"C\"",
])
def test_unsupported_source_profiles_refused_before_mutation(source, migration, statement):
    source.execute(statement)
    with pytest.raises(ValueError):
        migration.preview_owner_partitions(source, owner_id='alice')
    with pytest.raises(ValueError):
        migration.migrate_owner_partitions(source, owner_id='alice')
    assert source.execute("SELECT relkind FROM pg_class WHERE oid='messages'::regclass").fetchone() == ('r',)


def test_serial_allocators_advance_past_explicit_ids_transactionally(source, migration):
    source.execute("INSERT INTO attachments(id,user_id,message_id,filename,mime_type) VALUES(100,'alice','same','explicit','text/plain')")
    source.execute("INSERT INTO propositions(id,user_id,message_id,text,model) VALUES(100,'alice','same','explicit','test')")
    original = {name: source.execute(sql.SQL('SELECT last_value,is_called FROM {}').format(sql.Identifier(name))).fetchone()
                for name in ('attachments_id_seq','propositions_id_seq','messages_search_id_seq')}
    def fail(stage):
        if stage == 'attached':
            raise RuntimeError('rollback allocator')
    with pytest.raises(RuntimeError, match='rollback allocator'):
        migration.migrate_owner_partitions(source, owner_id='alice', _checkpoint=fail)
    for name, values in original.items():
        assert source.execute(sql.SQL('SELECT last_value,is_called FROM {}').format(sql.Identifier(name))).fetchone() == values
    migration.migrate_owner_partitions(source, owner_id='alice')
    assert source.execute("INSERT INTO attachments(user_id,message_id,filename,mime_type) VALUES('alice','same','next','text/plain') RETURNING id").fetchone()[0] > 100
    assert source.execute("INSERT INTO propositions(user_id,message_id,text,model) VALUES('alice','same','next','test') RETURNING id").fetchone()[0] > 100


def test_partitioned_preview_uses_read_only_inspection(source, migration):
    migration.migrate_owner_partitions(source, owner_id='alice')
    assert migration.preview_owner_partitions(source, owner_id='alice')['mode'] == 'already_partitioned'


def catalog_snapshot(conn):
    return {
        'relations': conn.execute("SELECT oid,relname,relnamespace,relowner,relfilenode,relacl,relrowsecurity,relforcerowsecurity FROM pg_class WHERE relnamespace='public'::regnamespace ORDER BY oid").fetchall(),
        'constraints': conn.execute("SELECT oid,conname,conrelid,confrelid,pg_get_constraintdef(oid) FROM pg_constraint WHERE connamespace='public'::regnamespace ORDER BY oid").fetchall(),
        'comments': conn.execute("SELECT * FROM pg_description WHERE objoid IN(SELECT oid FROM pg_class WHERE relnamespace='public'::regnamespace) ORDER BY objoid,objsubid").fetchall(),
        'defaults': conn.execute("SELECT d.adrelid,d.adnum,pg_get_expr(d.adbin,d.adrelid) FROM pg_attrdef d JOIN pg_class c ON c.oid=d.adrelid WHERE c.relnamespace='public'::regnamespace ORDER BY d.adrelid,d.adnum").fetchall(),
    }


def test_late_rollback_restores_catalog_and_dependent_rows(source, migration):
    source.execute("GRANT SELECT(id,user_id,subject) ON messages TO PUBLIC")
    before = catalog_snapshot(source)
    dependent_rows = {table: source.execute(sql.SQL('TABLE {}').format(sql.Identifier(table))).fetchall() for table in migration.DEPENDENTS}
    def fail(stage):
        if stage == 'attached':
            raise RuntimeError('late rollback')
    with pytest.raises(RuntimeError, match='late rollback'):
        migration.migrate_owner_partitions(source, owner_id='alice', _checkpoint=fail)
    assert catalog_snapshot(source) == before
    for table, values in dependent_rows.items():
        assert source.execute(sql.SQL('TABLE {}').format(sql.Identifier(table))).fetchall() == values


def test_column_grants_move_to_parent_and_private_leaves_deny_reader(source, migration):
    role = 'gms_owner_partitions_reader_' + secrets.token_hex(8)
    source.execute(sql.SQL('CREATE ROLE {} NOLOGIN').format(sql.Identifier(role)))
    try:
        source.execute(sql.SQL('GRANT USAGE ON SCHEMA public TO {}').format(sql.Identifier(role)))
        source.execute(sql.SQL('GRANT SELECT(id,user_id,subject) ON messages TO {}').format(sql.Identifier(role)))
        migration.migrate_owner_partitions(source, owner_id='alice')
        source.execute(sql.SQL('SET ROLE {}').format(sql.Identifier(role)))
        try:
            assert source.execute('SELECT id,user_id,subject FROM messages').fetchall() == [('same','alice','needle')]
            with pytest.raises(psycopg.errors.InsufficientPrivilege):
                source.execute('SELECT body_html FROM messages')
            with pytest.raises(psycopg.errors.InsufficientPrivilege):
                source.execute(sql.SQL('SELECT id FROM {}.{}').format(sql.Identifier(PARTITION_SCHEMA),sql.Identifier(partition_name('messages','alice'))))
        finally:
            source.execute('RESET ROLE')
    finally:
        source.execute(sql.SQL('DROP OWNED BY {}').format(sql.Identifier(role)))
        source.execute(sql.SQL('DROP ROLE {}').format(sql.Identifier(role)))


@pytest.mark.parametrize('statement', [
    "ALTER SEQUENCE attachments_id_seq INCREMENT BY -1 MINVALUE -9223372036854775808 MAXVALUE -1 START WITH -1 RESTART WITH -1",
    'ALTER SEQUENCE propositions_id_seq CACHE 20',
    "CREATE FUNCTION unexpected(messages) RETURNS text LANGUAGE sql AS $$ SELECT 'x'::text $$",
    "CREATE FUNCTION unexpected() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN RETURN NEW; END$$; CREATE TRIGGER unexpected BEFORE UPDATE ON messages FOR EACH ROW EXECUTE FUNCTION unexpected()",
    "ALTER TABLE messages ADD COLUMN extra text GENERATED ALWAYS AS (subject) STORED",
    "ALTER TABLE messages ADD CHECK(subject<>'never')",
])
def test_more_unsupported_dependencies_fail_read_only_preview(source, migration, statement):
    source.execute(statement)
    with pytest.raises(ValueError):
        migration.preview_owner_partitions(source, owner_id='alice')
    assert source.execute('SELECT to_regnamespace(%s)',(PARTITION_SCHEMA,)).fetchone() == (None,)


@pytest.mark.parametrize('statement', [
    "CREATE FUNCTION public.old_message_count() RETURNS bigint LANGUAGE sql BEGIN ATOMIC SELECT count(*) FROM public.messages; END",
    "CREATE POLICY external ON users USING(EXISTS(SELECT 1 FROM messages))",
    "CREATE FUNCTION unexpected(messages[]) RETURNS text LANGUAGE sql AS $$ SELECT 'x'::text $$",
])
def test_external_oid_bound_dependencies_refused(source, migration, statement):
    source.execute(statement)
    with pytest.raises(ValueError):
        migration.preview_owner_partitions(source, owner_id='alice')
    assert source.execute("SELECT relkind FROM pg_class WHERE oid='messages'::regclass").fetchone() == ('r',)


def test_renamed_identity_sequence_refused_before_mutation(source, migration):
    source.execute('ALTER SEQUENCE messages_search_id_seq RENAME TO renamed_message_allocator')
    with pytest.raises(ValueError):
        migration.preview_owner_partitions(source, owner_id='alice')
    assert source.execute("SELECT to_regclass('public.renamed_message_allocator')").fetchone()[0] is not None


def test_identity_sequence_comment_survives_recreation(source, migration):
    source.execute("COMMENT ON SEQUENCE messages_search_id_seq IS 'synthetic allocator metadata'")
    migration.migrate_owner_partitions(source, owner_id='alice')
    assert source.execute("SELECT obj_description('messages_search_id_seq'::regclass,'pg_class')").fetchone() == ('synthetic allocator metadata',)


def test_apply_guard_checks_actual_connection_address_without_network(migration):
    from types import SimpleNamespace
    from psycopg.pq import TransactionStatus
    connection = SimpleNamespace(info=SimpleNamespace(transaction_status=TransactionStatus.IDLE,
        host='127.0.0.1',hostaddr='192.0.2.1',port=55440,dbname='gms_owner_partitions_test_stub'))
    with pytest.raises(ValueError):
        migration._require(connection,apply=True)


def test_toast_heap_files_and_large_values_are_reused(source, migration):
    source.execute('UPDATE messages SET body_text=%s',(secrets.token_hex(12000),))
    source.execute('UPDATE propositions SET embedding=%s',(secrets.token_bytes(12000),))
    before = {table: rows(source,table) for table in migration.TABLES}
    files = source.execute("SELECT c.oid,c.relfilenode,t.oid,t.relfilenode FROM pg_class c JOIN pg_class t ON t.oid=c.reltoastrelid WHERE c.oid=ANY(%s::regclass[])",(list(migration.TABLES),)).fetchall()
    assert source.execute("SELECT pg_total_relation_size(reltoastrelid) FROM pg_class WHERE oid='messages'::regclass").fetchone()[0] > 8192
    migration.migrate_owner_partitions(source,owner_id='alice')
    for table, values in before.items():
        assert rows(source,table) == values
    for oid,node,toast_oid,toast_node in files:
        assert source.execute('SELECT c.relfilenode,t.oid,t.relfilenode FROM pg_class c JOIN pg_class t ON t.oid=c.reltoastrelid WHERE c.oid=%s',(oid,)).fetchone() == (node,toast_oid,toast_node)


def test_preview_does_not_take_provision_lock_and_apply_refuses_contention(source, migration):
    dsn = make_conninfo(os.environ['GMS_RANKED_PROBE_DSN'],dbname=source.info.dbname)
    with psycopg.connect(dsn,autocommit=True) as blocker:
        with blocker.transaction():
            blocker.execute("SELECT pg_advisory_xact_lock(hashtextextended('gmail-search partition catalog v1',0))")
            assert migration.preview_owner_partitions(source,owner_id='alice')['mode']=='attach_single_owner'
            with pytest.raises(psycopg.errors.LockNotAvailable):
                migration.migrate_owner_partitions(source,owner_id='alice')
    assert source.execute('SELECT to_regnamespace(%s)',(PARTITION_SCHEMA,)).fetchone() == (None,)
    assert migration.migrate_owner_partitions(source,owner_id='alice') is True


def test_rehearsal_reports_small_fixture_storage_and_wal(source, migration):
    import json
    import time
    inventory = migration.preview_owner_partitions(source,owner_id='alice')['source_inventory']
    lsn = source.execute('SELECT pg_current_wal_insert_lsn()').fetchone()[0]
    start = time.perf_counter()
    migration.migrate_owner_partitions(source,owner_id='alice')
    elapsed = time.perf_counter()-start
    wal = source.execute('SELECT pg_wal_lsn_diff(pg_current_wal_insert_lsn(),%s::pg_lsn)',(lsn,)).fetchone()[0]
    print(json.dumps({'fixture_rows':sum(item['row_count'] for item in inventory),
        'heap_bytes':sum(item['heap_bytes'] for item in inventory),
        'toast_bytes':sum(item['toast_bytes'] for item in inventory),
        'bm25_bytes':sum(index[4] for item in inventory for index in item['indexes'] if index[3]=='bm25'),
        'apply_seconds':elapsed,'cluster_wal_delta_bytes':int(wal)},sort_keys=True))
    assert elapsed>0 and wal>0
