"""Administrator partition checks on a disposable, pinned ParadeDB database."""
from concurrent.futures import ThreadPoolExecutor
import os
import secrets

import psycopg
from psycopg import sql
from psycopg.conninfo import conninfo_to_dict, make_conninfo
import pytest

from gmail_search.gateway import partitions


@pytest.fixture
def partition_database(request):
    dsn = os.getenv('GMS_TEST_PG_DSN')
    if not dsn:
        pytest.skip('GMS_TEST_PG_DSN synthetic ParadeDB fixture required')
    cfg = conninfo_to_dict(dsn)
    assert (cfg.get('host'), cfg.get('port'), cfg.get('dbname'), cfg.get('user')) == ('127.0.0.1', '55440', 'postgres', 'postgres')
    assert not set(cfg) & {'hostaddr', 'service', 'options'}
    name = 'gms_partition_provision_' + secrets.token_hex(8)
    target = make_conninfo(dsn, dbname=name)
    with psycopg.connect(dsn, autocommit=True) as admin:
        admin.execute(sql.SQL('CREATE DATABASE {} TEMPLATE template0').format(sql.Identifier(name)))
    try:
        with psycopg.connect(target, autocommit=True) as conn:
            conn.execute('CREATE EXTENSION pg_search')
            variant = getattr(request,'param',None)
            nocase = variant == 'nocase'
            if variant in ('nocase','users_nocase'):
                conn.execute("CREATE COLLATION public.owner_nocase(provider=icu,locale='und-u-ks-level2',deterministic=false)")
            def ddl(statement):
                if nocase:statement=statement.replace('user_id text NOT NULL','user_id text COLLATE public.owner_nocase NOT NULL')
                conn.execute(statement)
            assert conn.execute("SELECT extversion FROM pg_extension WHERE extname='pg_search'").fetchone() == ('0.23.0',)
            # 16.15 since 2026-09-16: the patched pg_search image is built on
            # ParadeDB's current Dockerfile, which pulls postgres:16-trixie.
            assert conn.info.server_version == 160015
            conn.execute("CREATE TABLE public.users(id text" + (" COLLATE public.owner_nocase" if variant == "users_nocase" else "") + " PRIMARY KEY)")
            conn.execute("INSERT INTO public.users VALUES ('alice'),('bob')")
            ddl('''CREATE TABLE public.messages(user_id text NOT NULL REFERENCES public.users ON DELETE CASCADE,
                id text NOT NULL,search_id bigint GENERATED BY DEFAULT AS IDENTITY,subject text,body_text text,from_addr text,to_addr text,
                PRIMARY KEY(user_id,id),UNIQUE(user_id,search_id)) PARTITION BY LIST(user_id)''')
            ddl('''CREATE TABLE public.attachments(user_id text NOT NULL REFERENCES public.users ON DELETE CASCADE,
                id bigint NOT NULL,message_id text NOT NULL,filename text NOT NULL,extracted_text text,
                PRIMARY KEY(user_id,id),UNIQUE(user_id,message_id,filename),UNIQUE(user_id,message_id,id),
                FOREIGN KEY(user_id,message_id) REFERENCES public.messages(user_id,id)) PARTITION BY LIST(user_id)''')
            ddl('''CREATE TABLE public.propositions(user_id text NOT NULL,id bigint NOT NULL,message_id text NOT NULL,text text,
                PRIMARY KEY(user_id,id),FOREIGN KEY(user_id,message_id) REFERENCES public.messages(user_id,id) ON DELETE CASCADE) PARTITION BY LIST(user_id)''')
            for table in ('messages','attachments','propositions'):
                conn.execute(sql.SQL('ALTER TABLE public.{} ENABLE ROW LEVEL SECURITY').format(sql.Identifier(table)))
                conn.execute(sql.SQL('ALTER TABLE public.{} FORCE ROW LEVEL SECURITY').format(sql.Identifier(table)))
            conn.execute("CREATE INDEX messages_bm25_idx ON public.messages USING bm25(search_id,id,subject,body_text,from_addr,to_addr) WITH(key_field='search_id')")
            conn.execute("CREATE INDEX attachments_bm25_idx ON public.attachments USING bm25(id,filename,extracted_text) WITH(key_field='id')")
            conn.execute("CREATE INDEX props_bm25_idx ON public.propositions USING bm25(id,text) WITH(key_field='id')")
        yield target
    finally:
        with psycopg.connect(dsn, autocommit=True) as admin:
            admin.execute(sql.SQL('DROP DATABASE {} WITH (FORCE)').format(sql.Identifier(name)))


def test_provisions_idempotently_with_real_native_parent_search(partition_database):
    with psycopg.connect(partition_database, autocommit=True) as conn:
        partitions.provision_owner_partitions(conn, 'alice')
        partitions.provision_owner_partitions(conn, 'bob')
        before = conn.execute("SELECT oid FROM pg_class WHERE relnamespace='gms_mail_partitions'::regnamespace ORDER BY oid").fetchall()
        partitions.provision_owner_partitions(conn, 'alice')
        assert partitions.verify_owner_partitions(conn, 'alice') is None
        assert conn.execute("SELECT oid FROM pg_class WHERE relnamespace='gms_mail_partitions'::regnamespace ORDER BY oid").fetchall() == before
        conn.execute("INSERT INTO public.messages(user_id,id,body_text) VALUES ('alice','same','needle'),('bob','same','foreign')")
        assert conn.execute("SELECT id FROM public.messages WHERE user_id='alice' AND search_id @@@ 'body_text:needle'").fetchall() == [('same',)]


def test_unknown_owner_and_missing_partition_fail_closed(partition_database):
    with psycopg.connect(partition_database, autocommit=True) as conn:
        with pytest.raises(ValueError, match='Owner'):
            partitions.provision_owner_partitions(conn, 'absent')
        with pytest.raises(ValueError, match='Missing'):
            partitions.verify_owner_partitions(conn, 'alice')
        assert conn.execute("SELECT to_regnamespace('gms_mail_partitions')").fetchone() == (None,)


@pytest.mark.parametrize('fault', ['bound','default','metadata','rls','column_grant','schema_grant','index','parent_index','parent_key','foreign_key','parent_rls','ancestry'])
def test_catalog_drift_rejected_without_repair(partition_database, fault):
    with psycopg.connect(partition_database, autocommit=True) as conn:
        partitions.provision_owner_partitions(conn, 'alice')
        child = sql.Identifier(partitions.PARTITION_SCHEMA, partitions.partition_name('messages','alice'))
        if fault in ('bound','default','ancestry'):
            conn.execute(sql.SQL('ALTER TABLE public.messages DETACH PARTITION {}').format(child))
            if fault == 'bound':
                conn.execute(sql.SQL("ALTER TABLE public.messages ATTACH PARTITION {} FOR VALUES IN ('bob')").format(child))
            elif fault == 'default':
                conn.execute(sql.SQL('ALTER TABLE public.messages ATTACH PARTITION {} DEFAULT').format(child))
        elif fault == 'metadata':
            conn.execute(sql.SQL("COMMENT ON TABLE {} IS 'forged'").format(child))
        elif fault == 'rls':
            conn.execute(sql.SQL('ALTER TABLE {} NO FORCE ROW LEVEL SECURITY').format(child))
        elif fault == 'column_grant':
            conn.execute(sql.SQL('GRANT SELECT(subject) ON {} TO PUBLIC').format(child))
        elif fault == 'schema_grant':
            conn.execute('GRANT USAGE ON SCHEMA gms_mail_partitions TO PUBLIC')
        elif fault == 'index':
            conn.execute(sql.SQL('ALTER TABLE public.messages DETACH PARTITION {}').format(child))
            index = conn.execute("SELECT c.relname FROM pg_index i JOIN pg_class c ON c.oid=i.indexrelid JOIN pg_am a ON a.oid=c.relam WHERE i.indrelid=%s::regclass AND a.amname='bm25'", (child.as_string(conn),)).fetchone()[0]
            conn.execute(sql.SQL('DROP INDEX {}').format(sql.Identifier(partitions.PARTITION_SCHEMA,index)))
        elif fault == 'parent_index':
            conn.execute('DROP INDEX public.messages_bm25_idx')
        elif fault == 'parent_key':
            conn.execute('ALTER TABLE public.messages DROP CONSTRAINT messages_user_id_search_id_key')
        elif fault == 'foreign_key':
            conn.execute('ALTER TABLE public.propositions DROP CONSTRAINT propositions_user_id_message_id_fkey')
        elif fault == 'parent_rls':
            conn.execute('ALTER TABLE public.messages NO FORCE ROW LEVEL SECURITY')
        for operation in (partitions.verify_owner_partitions, partitions.provision_owner_partitions):
            with pytest.raises(ValueError):
                operation(conn, 'alice')


def test_forged_name_rolls_back_all_new_children(partition_database):
    with psycopg.connect(partition_database, autocommit=True) as conn:
        conn.execute('CREATE SCHEMA gms_mail_partitions')
        forged = sql.Identifier(partitions.PARTITION_SCHEMA, partitions.partition_name('propositions','alice'))
        conn.execute(sql.SQL('CREATE TABLE {}(id int)').format(forged))
        with pytest.raises(ValueError):
            partitions.provision_owner_partitions(conn, 'alice')
        assert conn.execute("SELECT count(*) FROM pg_inherits i JOIN pg_class c ON c.oid=i.inhparent WHERE c.relname IN ('messages','attachments','propositions')").fetchone() == (0,)


def test_caller_rollback_and_competing_provisioners(partition_database):
    with psycopg.connect(partition_database, autocommit=True) as conn:
        with pytest.raises(RuntimeError):
            with conn.transaction():
                partitions.provision_owner_partitions(conn, 'alice')
                raise RuntimeError('injected rollback')
        assert conn.execute("SELECT to_regnamespace('gms_mail_partitions')").fetchone() == (None,)
    def provision(_):
        with psycopg.connect(partition_database, autocommit=True) as conn:
            partitions.provision_owner_partitions(conn, 'alice')
    with ThreadPoolExecutor(max_workers=2) as pool:
        list(pool.map(provision, range(2)))
    with psycopg.connect(partition_database, autocommit=True) as conn:
        partitions.verify_owner_partitions(conn, 'alice')


@pytest.fixture
def runtime_identity(partition_database):
    role = 'gms_partition_runtime_' + secrets.token_hex(8)
    password = secrets.token_urlsafe(40)
    with psycopg.connect(partition_database, autocommit=True) as conn:
        conn.execute(sql.SQL('CREATE ROLE {} LOGIN PASSWORD {} NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS').format(sql.Identifier(role),sql.Literal(password)))
    try:
        yield role, make_conninfo(partition_database,user=role,password=password)
    finally:
        with psycopg.connect(partition_database, autocommit=True) as conn:
            conn.execute(sql.SQL('DROP OWNED BY {}').format(sql.Identifier(role)))
            conn.execute(sql.SQL('DROP ROLE {}').format(sql.Identifier(role)))


def test_runtime_login_and_set_role_cannot_administer(partition_database, runtime_identity):
    role, dsn = runtime_identity
    with psycopg.connect(dsn, autocommit=True) as conn:
        for operation in (partitions.provision_owner_partitions,partitions.verify_owner_partitions):
            with pytest.raises(ValueError,match='superuser'):
                operation(conn,'alice')
    with psycopg.connect(partition_database, autocommit=True) as conn:
        conn.execute(sql.SQL('SET ROLE {}').format(sql.Identifier(role)))
        with pytest.raises(ValueError,match='superuser'):
            partitions.provision_owner_partitions(conn,'alice')


@pytest.mark.parametrize('object_kind',['schema','sequence','default','owner'])
def test_private_acl_sources_fail_closed(partition_database, runtime_identity, object_kind):
    role, _ = runtime_identity
    with psycopg.connect(partition_database, autocommit=True) as conn:
        partitions.provision_owner_partitions(conn,'alice')
        if object_kind=='schema':
            conn.execute(sql.SQL('GRANT USAGE ON SCHEMA gms_mail_partitions TO {}').format(sql.Identifier(role)))
        elif object_kind=='sequence':
            conn.execute('CREATE SEQUENCE gms_mail_partitions.unexpected_sequence')
            conn.execute(sql.SQL('GRANT USAGE ON SEQUENCE gms_mail_partitions.unexpected_sequence TO {}').format(sql.Identifier(role)))
        elif object_kind=='default':
            conn.execute(sql.SQL('ALTER DEFAULT PRIVILEGES IN SCHEMA gms_mail_partitions GRANT SELECT ON TABLES TO {}').format(sql.Identifier(role)))
        else:
            conn.execute(sql.SQL('ALTER SCHEMA gms_mail_partitions OWNER TO {}').format(sql.Identifier(role)))
            conn.execute(sql.SQL('REVOKE ALL ON SCHEMA gms_mail_partitions FROM {}').format(sql.Identifier(role)))
        try:
            with pytest.raises(ValueError):
                partitions.provision_owner_partitions(conn,'bob')
        finally:
            if object_kind=='owner':
                conn.execute('ALTER SCHEMA gms_mail_partitions OWNER TO postgres')
        assert conn.execute('SELECT to_regclass(%s)', ('gms_mail_partitions.'+partitions.partition_name('messages','bob'),)).fetchone() == (None,)


def test_mixed_bound_elsewhere_and_noncanonical_bm25_rejected(partition_database):
    with psycopg.connect(partition_database,autocommit=True) as conn:
        partitions.provision_owner_partitions(conn,'alice')
        conn.execute("INSERT INTO public.users VALUES ('charlie')")
        child=sql.Identifier('gms_mail_partitions',partitions.partition_name('messages','bob'))
        conn.execute(sql.SQL("CREATE TABLE {} PARTITION OF public.messages FOR VALUES IN ('bob','charlie')").format(child))
        conn.execute(sql.SQL('ALTER TABLE {} ENABLE ROW LEVEL SECURITY').format(child))
        conn.execute(sql.SQL('ALTER TABLE {} FORCE ROW LEVEL SECURITY').format(child))
        conn.execute(sql.SQL('COMMENT ON TABLE {} IS {}').format(child,sql.Literal(partitions.partition_binding('messages','bob'))))
        with pytest.raises(ValueError,match='binding'):
            partitions.verify_owner_partitions(conn,'alice')
        conn.execute(sql.SQL('ALTER TABLE public.messages DETACH PARTITION {}').format(child))
        conn.execute(sql.SQL('DROP TABLE {}').format(child))
        conn.execute('DROP INDEX public.messages_bm25_idx')
        conn.execute("CREATE INDEX messages_bm25_idx ON public.messages USING bm25(search_id,body_text) WITH(key_field='search_id')")
        with pytest.raises(ValueError,match='BM25'):
            partitions.verify_owner_partitions(conn,'alice')


def test_bound_literals_and_different_owner_concurrency(partition_database):
    owner = "owner'\\quoted_雪"
    with psycopg.connect(partition_database,autocommit=True) as conn:
        conn.execute('INSERT INTO public.users VALUES (%s)',(owner,))
    def create(owner_id):
        with psycopg.connect(partition_database,autocommit=True) as conn:
            partitions.provision_owner_partitions(conn,owner_id)
    with ThreadPoolExecutor(max_workers=2) as pool:
        list(pool.map(create,[owner,'bob']))
    with psycopg.connect(partition_database,autocommit=True) as conn:
        partitions.verify_owner_partitions(conn,owner)


@pytest.mark.parametrize('partition_database',['nocase','users_nocase'],indirect=True)
def test_case_insensitive_owner_partition_comparison_is_refused(partition_database):
    with psycopg.connect(partition_database,autocommit=True) as conn:
        with pytest.raises(ValueError,match='collation|comparison'):
            partitions.provision_owner_partitions(conn,'alice')


def test_lock_budget_and_caller_settings_survive_contention(partition_database):
    import time
    with psycopg.connect(partition_database,autocommit=True) as blocker, psycopg.connect(partition_database,autocommit=True) as conn:
        conn.execute("SET lock_timeout='7s'")
        conn.execute("SET statement_timeout='5s'")
        with blocker.transaction():
            blocker.execute('SELECT pg_advisory_xact_lock(hashtextextended(%s,0))',('gmail-search partition owner alice',))
            start=time.monotonic()
            with pytest.raises(psycopg.errors.LockNotAvailable):
                partitions.provision_owner_partitions(conn,'alice')
            assert time.monotonic()-start<4
        assert conn.execute("SELECT current_setting('lock_timeout'),current_setting('statement_timeout')").fetchone()==('7s','5s')
        partitions.provision_owner_partitions(conn,'alice')
        assert conn.execute("SELECT current_setting('lock_timeout'),current_setting('statement_timeout')").fetchone()==('7s','5s')


def test_readonly_inspector_uses_same_verification(partition_database):
    with psycopg.connect(partition_database,autocommit=True) as conn:
        partitions.provision_owner_partitions(conn,'alice')
        with pytest.raises(ValueError,match='snapshot'):
            partitions.inspect_owner_partitions(conn,'alice')
        with conn.transaction():
            conn.execute('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY')
            assert partitions.inspect_owner_partitions(conn,'alice') is None
        conn.execute('GRANT USAGE ON SCHEMA gms_mail_partitions TO PUBLIC')
        with conn.transaction():
            conn.execute('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY')
            with pytest.raises(ValueError,match='grant'):
                partitions.inspect_owner_partitions(conn,'alice')


def test_remove_empty_owner_then_delete_user_preserves_other_owners(partition_database):
    with psycopg.connect(partition_database,autocommit=True) as conn:
        partitions.provision_owner_partitions(conn,'alice')
        partitions.provision_owner_partitions(conn,'bob')
        conn.execute("INSERT INTO public.messages(user_id,id,body_text) VALUES ('alice','kept','private')")
        alice = conn.execute('SELECT to_regclass(%s)::oid',('gms_mail_partitions.'+partitions.partition_name('messages','alice'),)).fetchone()[0]
        with conn.transaction():
            partitions.remove_empty_owner_partitions(conn,'bob')
            partitions.remove_empty_owner_partitions(conn,'bob')
            conn.execute("DELETE FROM public.users WHERE id='bob'")
        partitions.verify_owner_partitions(conn,'alice')
        assert conn.execute('SELECT to_regclass(%s)::oid',('gms_mail_partitions.'+partitions.partition_name('messages','alice'),)).fetchone()[0] == alice
        assert conn.execute('SELECT user_id,id FROM public.messages').fetchall()==[('alice','kept')]
        conn.execute("INSERT INTO public.users VALUES ('charlie')")
        partitions.provision_owner_partitions(conn,'charlie')
        partitions.verify_owner_partitions(conn,'charlie')


def test_remove_refuses_nonempty_without_dropping_any_leaf(partition_database):
    with psycopg.connect(partition_database,autocommit=True) as conn:
        partitions.provision_owner_partitions(conn,'bob')
        conn.execute("INSERT INTO public.messages(user_id,id) VALUES ('bob','kept')")
        with pytest.raises(ValueError,match='empty'):
            partitions.remove_empty_owner_partitions(conn,'bob')
        partitions.verify_owner_partitions(conn,'bob')
        assert conn.execute("SELECT id FROM public.messages WHERE user_id='bob'").fetchall()==[('kept',)]


def test_remove_is_rolled_back_with_caller_transaction(partition_database):
    with psycopg.connect(partition_database,autocommit=True) as conn:
        partitions.provision_owner_partitions(conn,'bob')
        with pytest.raises(RuntimeError):
            with conn.transaction():
                partitions.remove_empty_owner_partitions(conn,'bob')
                conn.execute("DELETE FROM public.users WHERE id='bob'")
                raise RuntimeError('rollback removal')
        partitions.verify_owner_partitions(conn,'bob')
        conn.execute("INSERT INTO public.messages(user_id,id) VALUES ('bob','after-rollback')")
        conn.execute("INSERT INTO public.attachments(user_id,id,message_id,filename) VALUES ('bob',1,'after-rollback','file')")
        conn.execute("INSERT INTO public.propositions(user_id,id,message_id,text) VALUES ('bob',1,'after-rollback','retained FK')")


def test_remove_refuses_partial_set_and_wrong_binding(partition_database):
    with psycopg.connect(partition_database,autocommit=True) as conn:
        partitions.provision_owner_partitions(conn,'bob')
        child=sql.Identifier(partitions.PARTITION_SCHEMA,partitions.partition_name('propositions','bob'))
        conn.execute(sql.SQL('ALTER TABLE public.propositions DETACH PARTITION {}').format(child))
        conn.execute(sql.SQL('DROP TABLE {}').format(child))
        with pytest.raises(ValueError,match='partial'):
            partitions.remove_empty_owner_partitions(conn,'bob')
        partitions.provision_owner_partitions(conn,'bob')
        conn.execute(sql.SQL('COMMENT ON TABLE {} IS {}').format(child,sql.Literal(partitions.partition_binding('propositions','alice'))))
        with pytest.raises(ValueError,match='binding'):
            partitions.remove_empty_owner_partitions(conn,'bob')
        assert conn.execute('SELECT to_regclass(%s)',('gms_mail_partitions.'+partitions.partition_name('messages','bob'),)).fetchone()[0]


def test_remove_unknown_dependent_object_rolls_back_earlier_detaches(partition_database):
    with psycopg.connect(partition_database,autocommit=True) as conn:
        partitions.provision_owner_partitions(conn,'bob')
        child=sql.Identifier(partitions.PARTITION_SCHEMA,partitions.partition_name('messages','bob'))
        conn.execute(sql.SQL('CREATE VIEW public.hold_owner_leaf AS SELECT id FROM {}').format(child))
        with pytest.raises(psycopg.errors.DependentObjectsStillExist):
            partitions.remove_empty_owner_partitions(conn,'bob')
        partitions.verify_owner_partitions(conn,'bob')
        assert conn.execute("SELECT to_regclass('public.hold_owner_leaf')").fetchone()[0]
        for table in ('messages','attachments','propositions'):
            assert conn.execute('SELECT to_regclass(%s)',(partitions.PARTITION_SCHEMA+'.'+partitions.partition_name(table,'bob'),)).fetchone()[0]
